# Generated by Django 4.1.5 on 2023-01-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact',
        ),
        migrations.AddField(
            model_name='lead',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='ville',
            field=models.CharField(max_length=200, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='product',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destination', verbose_name='Déstination'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
