# Generated by Django 4.1.5 on 2023-01-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_alter_destination_options_alter_lead_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Type de Lead",
            ),
        ),
    ]
