# Generated by Django 4.1.5 on 2023-01-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_lead_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.destination",
                verbose_name="Déstination",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customproduct",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.producttype",
                verbose_name="Type De produit",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contact",
                verbose_name="Contact",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.destination",
                verbose_name="Destination",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.producttype",
                verbose_name="Type De produit",
            ),
        ),
        migrations.AlterField(
            model_name="customproduct",
            name="start_date",
            field=models.DateTimeField(verbose_name="Date de départ"),
        ),
    ]
