# Generated by Django 4.1.5 on 2023-02-01 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wilaya", "0001_initial"),
        ("core", "0005_customproduct_destination_customproduct_product_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusVisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Label")),
            ],
        ),
        migrations.RemoveField(
            model_name="lead",
            name="destination",
        ),
        migrations.AddField(
            model_name="contact",
            name="big_client",
            field=models.BooleanField(default=False, verbose_name="grand voyageur"),
        ),
        migrations.AddField(
            model_name="contact",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wilaya.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tarif Single"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="room",
            field=models.CharField(
                choices=[("SN", "Single"), ("DB", "Double"), ("TR", "Triple")],
                default="DB",
                max_length=50,
                verbose_name="Chambre",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="double_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tarif Double"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hotel",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="hôtel"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="places_number",
            field=models.IntegerField(default=0, verbose_name="PAX"),
        ),
        migrations.AddField(
            model_name="product",
            name="return_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de départ"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="single_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tarif Single"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tripl_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tarif Triple"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="adress",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Adresse"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom et prénom"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="lead",
            name="visa_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.statusvisa",
            ),
        ),
    ]
