# Generated by Django 4.1.5 on 2023-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_statusvisa_remove_lead_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="passport",
            field=models.FileField(default=1, upload_to="images/passport"),
            preserve_default=False,
        ),
    ]
