# Generated by Django 4.1.5 on 2023-02-02 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_lead_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Résponsable",
            ),
        ),
    ]
